# Generated by Django 5.2.12 on 2026-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal note visible only to agents and managers.'),
        ),
    ]
