# Generated by Django 5.2.12 on 2026-03-11 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_approval'),
        ('tickets', '0009_add_ticket_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=100)),
                ('match_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20, null=True)),
                ('strategy', models.CharField(choices=[('direct_agent', 'Direct agent'), ('team_least_loaded', 'Team least-loaded agent'), ('global_least_loaded', 'Global least-loaded agent')], default='global_least_loaded', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignment_rules', to=settings.AUTH_USER_MODEL)),
                ('assign_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignment_rules', to='accounts.team')),
                ('match_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_rules', to='tickets.ticketcategory')),
            ],
            options={
                'ordering': ['priority_order', 'id'],
            },
        ),
    ]
