# Generated by Django 5.2.12 on 2026-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_assignment_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_suggested_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_suggested_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_for_customer', 'Pending (Waiting for Customer)'), ('escalated', 'Escalated to Manager'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20),
        ),
    ]
